# Get me a Kube cluster with Kubeflow and Pachyderm on it.

name: KFData

base:

  preload_files:
  - download: https://github.com/kubeflow/manifests/blob/master/kfdef/kfctl_k8s_istio.v1.1.0.yaml
    to: ./yaml/  # NB: Will mkdir yaml if it doesn't exist

  # Or, to upload from local ctx where testctl is run from (e.g. in git repo):
  # - copy: ./kfctl_k8s_istio.v1.1.0.yaml
  #   to: ./yaml/

  prewarm_script: |-
    #!/bin/bash
    export KF_NAME=kf

    # Set the path to the base directory where you want to store one or more
    # Kubeflow deployments. For example, /opt/.
    # Then set the Kubeflow application directory for this deployment.
    export BASE_DIR=$(pwd)
    export KF_DIR=${BASE_DIR}/${KF_NAME}

    # Set the configuration file to use, such as the file specified below:
    export CONFIG_URI="${BASE_DIR}/yaml/kfctl_k8s_istio.v1.1.0.yaml"
    # Generate and deploy Kubeflow:
    mkdir -p ${KF_DIR}
    cd ${KF_DIR}
    kfctl apply -V -f ${CONFIG_URI}
    cd ${BASE_DIR}

  kubernetes_version: '1.18'

runtime:
  cpus: 2
  memory: 4GB
  disk: 30GB

prewarm_pool_size: 3
