# Get me a Kube cluster with Kubeflow (and later, for demo purposes Pachyderm) on it.

name: KFData

base:

  # TODO: make these optional
  preload_docker_images: []
  kernel_image: "quay.io/testfaster/ignite-kernel"

  os_dockerfile: |-
    FROM quay.io/testfaster/kube-ubuntu

    # kubeflow
    RUN curl -LO https://github.com/kubeflow/kfctl/releases/download/v1.1.0/kfctl_v1.1.0-0-g9a3621e_linux.tar.gz && \
        tar xf kfctl_v1.1.0-0-g9a3621e_linux.tar.gz && \
        mv kfctl /usr/local/bin

    RUN mkdir -p /workdir/yaml
    RUN wget -O /workdir/yaml/kfctl_k8s_istio.v1.1.0.yaml \
        https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_k8s_istio.v1.1.0.yaml

  prewarm_script: |-
    #!/bin/bash
    export KF_NAME=kf

    # Set the path to the base directory where you want to store one or more
    # Kubeflow deployments. For example, /opt/.
    # Then set the Kubeflow application directory for this deployment.
    export BASE_DIR=/workdir
    export KF_DIR=${BASE_DIR}/${KF_NAME}

    # Set the configuration file to use, such as the file specified below:
    export CONFIG_URI="${BASE_DIR}/yaml/kfctl_k8s_istio.v1.1.0.yaml"
    # Generate and deploy Kubeflow:
    mkdir -p ${KF_DIR}
    cd ${KF_DIR}
    kfctl apply -V -f ${CONFIG_URI}
    cd ${BASE_DIR}

  kubernetes_version: '1.18'

runtime:
  cpus: 2
  memory: 4GB
  disk: 30GB

prewarm_pool_size: 3
